---
- name: Download kubectl binary
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_path }}"
    mode: '0755'

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
  ignore_errors: yes

- debug:
    msg: "kubectl installed successfully! Version info: {{ kubectl_version.stdout }}"

