---
- name: Add Jenkins repository
  get_url:
    url: "{{ jenkins_repo }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  rpm_key:
    state: present
    key: "{{ jenkins_key }}"

- name: Install Java and Jenkins
  yum:
    name: "{{ jenkins_packages }}"
    state: present

- name: Enable and start Jenkins service
  service:
    name: "{{ jenkins_service }}"
    state: started
    enabled: true
  notify: Restart Jenkins

