---
- name: Automated Web Server Configuration
  hosts: hosts
  become: true
  tasks:
    - name: Install nginx
      dnf:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Customize web page
      copy:
        content: |
          <html>
          <head>
              <title>Welcome to Ansible Web Server</title>
          </head>
          <body>
              <h1> Hello from Ansible!</h1>
              <p>This web server is configured automatically using Ansible.</p>
          </body>
          </html>
        dest: /var/www/html/index.nginx-debian.html
